#!/bin/bash
# imdb_processing

#=====
# The actor function returns xsv_selected_actor.csv containing the actor nconst

function actor_nconst( )

{
    echo "actor_nconst"
    # actor "<name>"
    # output xsv_selected_actor
    # returns nconst


    #Construct xsv command stack

    fxl_name="fxl_name.basics.csv"

    actor_name="'^*$1$'"
    printf "xsv select nconst,primaryName,primaryProfession ${imdb_dataset_in}$fxl_name \
    | xsv search --select 2 ${actor_name} \
    | xsv search --select 3 '^act.*$' \
    | xsv select 1,2,3 \
    | xsv slice  --no-headers --start 1 \n" > ${imdb_dataset_out_files}xsv_actor_nconst.sh
    
    # Execute xsv command stack
    chmod +x ${imdb_dataset_out_files}xsv_actor_nconst.sh
    ${imdb_dataset_out_files}xsv_actor_nconst.sh > ${imdb_dataset_out_files}xsv_selected_actor_nconst.csv
    cat xsv_selected_actor_nconst.csv

    # # Process xsv command stack
    selected_actor_nconst=$( wc -l ${imdb_dataset_out_files}xsv_selected_actor_nconst.csv | awk '{print $1}' )

    
    echo "Actor nconst count in ${fxl_name}: ${selected_actor_nconst}"

    case $selected_actor_nconst in

        0)
            echo "Actor $1 is not in dataset fxl_name.basics.csv" 
            exit
            ;;

        *)
            echo "Actor $1 is in dataset $fxl_name"
            return
            ;;
    esac
    
}




# # The actor function returns nconst
#actor_nconst "John Wayne"
