#!/bin/bash
# imdb_processing

#=====
# The actor function returns xsv_selected_actor.csv containing the actor nconst

function nconst( )

{
    echo "name_basics_nconst"
    # name_basics_nconst primaryName primaryProfession
    # output xsv_selected_actor
    # returns nconst


    #Construct xsv command stack

    fxl_name="fxl_name.basics.csv"

    primaryName="'^*$1$'"
    primaryProfession="^*$2$"

    #printf "xsv select nconst,primaryName,primaryProfession ${imdb_dataset_in}$fxl_name \
    printf "xsv select 1-6 ${imdb_dataset_in}$fxl_name \
   | xsv search --select 2 ${primaryName} \
    | xsv search --select 5 ${primaryProfession} \
    | xsv select 1,2,5  | xsv table 
    # | xsv slice  --no-headers --start 1 \n" > ${imdb_dataset_out_files}xsv_actor_nconst.sh
    
    # Execute xsv command stack
    chmod +x ${imdb_dataset_out_files}xsv_actor_nconst.sh
    ${imdb_dataset_out_files}xsv_actor_nconst.sh > ${imdb_dataset_out_files}xsv_selected_actor_nconst.csv
    cat ${imdb_dataset_out_files}xsv_selected_actor_nconst.csv

    # # Process xsv command stack
    selected_actor_nconst=$( wc -l ${imdb_dataset_out_files}xsv_selected_actor_nconst.csv | awk '{print $1}' )

    
    echo "$1 $2 name_basics_nconst count in ${fxl_name}: ${selected_actor_nconst}"

    case $selected_actor_nconst in

        0)
            echo "$1 $2 is not in dataset fxl_name.basics.csv" 
            exit
            ;;

        *)
            echo "$1 $2 is in dataset $fxl_name"
            return
            ;;
    esac
    
}




# # The actor function returns nconst
#actor_nconst "John Wayne"
